return {
	s({ trig = "@a", dscr = "Alpha Greek Letter", regTrig = false, priority = 100, snippetType = "autosnippet", condition = tex_utils.in_mathzone }, { t("{\\alpha}") }),
	s({ trig = "@b", desc = "insert beta", snippetType = "autosnippet", condition = tex_utils.in_mathzone }, { t("{\\beta}") }),
	s({ trig = "@q", desc = "theta", snippetType = "autosnippet", condition = tex_utils.in_mathzone }, { t("{\\theta}") }),
	s({ trig = "@g", snippetType = "autosnippet", condition = tex_utils.in_mathzone }, { t("{\\gamma}") }),
	s({ trig = "@G", snippetType = "autosnippet", condition = tex_utils.in_mathzone }, { t("{\\Gamma}") }),
	s({ trig = "@s", snippetType = "autosnippet", condition = tex_utils.in_mathzone }, { t("{\\sigma}") }),
	s({ trig = "@S", snippetType = "autosnippet", condition = tex_utils.in_mathzone }, { t("{\\Sigma}") }),
	s({ trig = "@p", snippetType = "autosnippet", condition = tex_utils.in_mathzone }, { t("{\\pi}") }),
	s({ trig = "@P", snippetType = "autosnippet", condition = tex_utils.in_mathzone }, { t("{\\Pi}") }),
	s({ trig = "@h", snippetType = "autosnippet", condition = tex_utils.in_mathzone }, { t("{\\eta}") }),
	s({ trig = "@r", snippetType = "autosnippet", condition = tex_utils.in_mathzone }, { t("{\\rho}") }),
	s({ trig = "@D", snippetType = "autosnippet", condition = tex_utils.in_mathzone }, { t("{\\Delta}") }),
	s({ trig = "@d", snippetType = "autosnippet", condition = tex_utils.in_mathzone }, { t("{\\delta}") }),
	s({ trig = "@t", snippetType = "autosnippet", condition = tex_utils.in_mathzone }, { t("{\\tau}") }),
	s({ trig = "@v", snippetType = "autosnippet", condition = tex_utils.in_mathzone }, { t("{\\nu}") }),
	s({ trig = "@w", snippetType = "autosnippet", condition = tex_utils.in_mathzone }, { t("{\\psi}") }),
	s({ trig = "@o", snippetType = "autosnippet", condition = tex_utils.in_mathzone }, { t("{\\omega}") }),
	s({ trig = "@O", snippetType = "autosnippet", condition = tex_utils.in_mathzone }, { t("{\\Omega}") }),
	s({ trig = "@e", snippetType = "autosnippet", condition = tex_utils.in_mathzone }, { t("{\\varepsilon}") }),
	s({ trig = "@f", snippetType = "autosnippet", condition = tex_utils.in_mathzone }, { t("{\\phi}") }),
	s({ trig = "@x", snippetType = "autosnippet", condition = tex_utils.in_mathzone }, { t("{\\xi}") }),
	s({ trig = "@c", snippetType = "autosnippet", condition = tex_utils.in_mathzone }, { t("{\\chi}") }),
	s({ trig = "@l", snippetType = "autosnippet", condition = tex_utils.in_mathzone }, { t("{\\lambda}") }),
	s({ trig = "@m", snippetType = "autosnippet", condition = tex_utils.in_mathzone }, { t("{\\mu}") }),
	s({ trig = "nab", snippetType = "autosnippet", condition = tex_utils.in_mathzone }, { t("{\\nabla}") }),
	s({ trig = "grad", snippetType = "autosnippet", condition = tex_utils.in_mathzone }, { t("\\underline{\\nabla}") }),
}
