
name: Build/Test on github
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build/Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Build Nix packages
        run: nix build .#full
