name: Check Formatting
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-and-test:
    name: Build/Test
    runs-on: nixos-host
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check formatting
        run: alejandra .
